server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/uwtracker
spring.datasource.username=uwtracker
spring.datasource.password=uwtracker
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
